### ISSUE TITLE
Can it support yarn build command？

### ISSUE THREAD

**Issue by 0x233-lh** [paketo-buildpacks/yarn#59]
## What happened?
There is another scenario that uses `yarn` or `npm`, that is, projects with static resource files like `vuejs` and` augur`.
Such static files project usually need to use the `yarn build` command to generate the `dist` directory, and the staticfile image can be built by `matching gcr.io/paketo-community/staticfile`.

**Comment by arjun024** [comment]
It looks like `yarn build` is not a standard yarn command, and is a hook specified in package.json on the scripts property like follows:
```
{
    "name": "mypackage",
    "scripts": {
       "build": "mybuildcommand --args"
    }
}
```

You should use standard hooks like `preinstall`, `postinstall` etc. which is run as part of the build process of  [`yarn-install`](https://github.com/paketo-buildpacks/yarn-install) buildpack. See https://classic.yarnpkg.com/en/docs/package-json/#toc-scripts

**Comment by arjun024** [comment]
@0x233-lh There's a new proposal to support the buildpack executing commands like you requested. If you can provide any feedback, that would be valuable. https://github.com/paketo-buildpacks/nodejs/blob/rfc-npm-scripts/rfcs/0004-npm-scripts.md

**Comment by Adam262** [comment]
Hey @arjun024 Thanks for pointing to the `yarn` hooks. We're dealing with this use case too, since we have at least one Node.JS app that uses a `yarn build` script that our old, bespoke Node.JS buildpack handled. The hooks seemed like a great fix, but realized `yarn postinstall`, etc does not run on a cached build.  

I saw the RFC to support `yarn build` was merged - any idea of timeline to implementing it? 

I am thinking my option in meantime is to write a small downstream pack on our side that requires `node` + `node_modules` and then runs `yarn build`.  Would be awesome to hear what you think.
